### ISSUE TITLE
Make sign-up logic handle user changing MetaMask accounts.

### ISSUE THREAD

**Issue by Adam0000** [PolymathNetwork/polymath-issuer#22]
In the current code the user is sent to the sign-up page if they don't have the account key set in their localStorage. Changing MetaMask accounts doesn't trigger that, and even if it did the account information of the previous account would be overwritten by the account they changed to. This is a problem since that object needs to be signed by the user's active account to authenticate with the polymath-offchain server.

I suggest storing and retrieving the account object in such a way that there is one for each account address.

**Comment by bshevchenko** [comment]
Agree
