### ISSUE TITLE
DatePickerInput.js:60 TypeError: _onClick is not a function

### ISSUE THREAD

**Issue by bshevchenko** [PolymathNetwork/polymath-issuer#32]
Now even DatePickerRange inputs lags and causes this error.

**Comment by davekaj** [comment]
this has been fixed in the whitelist branch. i will close the issue when this branch gets merged into master

**Comment by davekaj** [comment]
a fix has been merged into master. But right now boris still gets "TypeError: _onClick is not a function" (but without the lagging)

we will have to make sure it is working for everyone before this is closed

**Comment by bshevchenko** [comment]
No, it still lags in some cases

**Comment by bshevchenko** [comment]
Fixed by recent @Adam0000 's PR
