### ISSUE TITLE
Infura: connection not open on send(), web3WS newBlockHeaders, Event "Transfer" subscription error 

### ISSUE THREAD

**Issue by bshevchenko** [PolymathNetwork/polymath-issuer#36]
Open http://localhost:3000/dashboard/KORO
Then click STO at the sidebar and you'll see these errors in your console

**Comment by davekaj** [comment]
Yes, I am also getting this error, which is causing the whitelist app to crash.

The whitelist app was crashing because it was expecting to get transfer manager, as seen below:

**Comment by davekaj** [comment]
this is what the errors look like when connection closes
<img width="470" alt="screen shot 2018-04-25 at 5 14 19 pm" src="https://user-images.githubusercontent.com/22417382/39273240-3b527a00-48ac-11e8-91a6-1cbb74497a78.png">

**Comment by bshevchenko** [comment]
@pabloruiz55 we need to deploy polymath-core contracts to the kovan and/or rinkeby networks and test app there. It it won't work then we should try some nodes alternative to Infura's. 
P.S. It's better to always have contracts at least on the 2 test networks as a backup.

**Comment by bshevchenko** [comment]
Added Rinkeby. It works much better than Ropsten some time ago. But it still disconnects me sometimes. Need further research
P.S. For the time being I added nice error with request to refresh the page.

**Comment by bshevchenko** [comment]
For research we can deploy our own WS geth node.
And probably as an option we can write automatic reconnector.

**Comment by bshevchenko** [comment]
Solved by quiknode.io
