### ISSUE TITLE
Import Whitelist from .csv failed, Front End UI Testing

### ISSUE THREAD

**Issue by hrsummers** [PolymathNetwork/polymath-issuer#58]
- Description of the location and potential impact of the vulnerability
	Location: Whitelist portion of the Compliance Page of ST-20 Standard Security Token Issuer Platform
	Impact: Inability to upload a whitelist from .csv
- Observed behavior: The “Import Whitelist” button on pop up screen for importing is “greyed out” and shows a red slashed circle when you roll your mouse over it.
- Expected behavior: To be able to click "Import Whitelist" for the uploaded .csv (with the correct formatting) from the pop up screen and have it populate my investor list.
- How to replicate: Click on Compliance Tab. From the Whitelist portion of the Compliance page, click “Import Whitelist” Button. Screen pops up that prompts you to upload a .csv file. Upload your properly formated .csv file. It appears to successfully upload the .csv file. However, the “Import Whitelist” button on this page remains “greyed out” and shows a red slashed circle when you roll your mouse over it.

**Comment by PolymathTeam** [comment]
➤ Gopi commented:

Successfully tested importing whitelist. Closing the issue.
