### ISSUE TITLE
As an Issuer, I can enter up to 10 characters in the token symbol (letters, numbers, "." and "-") so that I can issue multiple classes of shares

### ISSUE THREAD

**Issue by kotaru77** [PolymathNetwork/polymath-issuer#66]
## Solution 
Max 10 Char for Token Symbol.

**Comment by kotaru77** [comment]
➤ Boris Shevchenko commented:

[Matthew Woo](https://app.asana.com/0/461575372520165/list) isn't Open Questions is the same as Research?

**Comment by kotaru77** [comment]
➤ Matthew Woo commented:

[Boris Shevchenko](https://app.asana.com/0/528285401193323/list)
 - Research: Are task related to writing the requirements of the task (deliverable)
 - Open Questions: Are questions that come up while writing the requirements or during implementation (question)

Let me know if that makes sense, or if you still feel like the two should be merged. I'm open to the idea but separating the two provides clarity from deliverables vs. questions.

**Comment by kotaru77** [comment]
➤ Thomas Borrel commented:

Verified length
Verified use of "-" and "."
Verified mix of "." and "-"
Verified mix of alphanumeric characters and "-"
Verified mix of alphanumeric characters and "."

**Comment by PolymathTeam** [comment]
➤ Thomas Borrel commented:

From Thomas McInerney:
If the issuer has a CUSIP, then we can request a symbol through FINRA (they will assign). usually the symbol is 5 letters. If not, The issuer can decide on 5 case insensitive alphanumeric characters of their own. 
[However] We will not be restricting ticker symbols at this time. Any utf8 character combination (within reason) will be accepted.
