### ISSUE TITLE
dApp asks for Auth signature again if user returns to the Splash screen

### ISSUE THREAD

**Issue by kotaru77** [PolymathNetwork/polymath-issuer#68]
1. Open Splash Screen in a new tab
2. Click CREATE SECURITY TOKEN
3. Sign verification code
4. Click on the Polymath logo at the navbar
5. Click CREATE SECURITY TOKEN

**Comment by PolymathTeam** [comment]
➤ Gopi commented:

Works as expected. Closing the issue.
