### ISSUE TITLE
Toast notifications styles

### ISSUE THREAD

**Issue by kotaru77** [PolymathNetwork/polymath-issuer#69]
Toast notification:
1. Change green accent color to #00AA5E
2. Change font to Overpass Link to FullStory is here: [FullStory Session](https://ift.tt/2IplXUm)

**Comment by kotaru77** [comment]
➤ Thomas Borrel commented:

Not critical for launch. Can be fixed after.

**Comment by kotaru77** [comment]
➤ Shannon Clarke commented:

[Boris Shevchenko](https://app.asana.com/0/528285401193323/list) please review PR https://github.com/PolymathNetwork/polymath-ui/pull/18

**Comment by kotaru77** [comment]
➤ Thomas Borrel commented:

Checked today - Toast notification looks good!

**Comment by kotaru77** [comment]
➤ Boris Shevchenko commented:

[Thomas Borrel](https://app.asana.com/0/610793545000470/list) PR for this is not even merged yet

**Comment by kotaru77** [comment]
➤ Shannon Clarke commented:

This change was in a previous PR. Will resubmit as new PR as required

**Comment by kotaru77** [comment]
➤ Shannon Clarke commented:

New PR: https://github.com/PolymathNetwork/polymath-ui/pull/28

**Comment by kotaru77** [comment]
➤ Boris Shevchenko commented:

[Stanislav Timofeev](https://app.asana.com/0/556075935441246/list) please test this one on https://dev--polymath-issuer.netlify.com/

**Comment by PolymathTeam** [comment]
➤ Stanislav Timofeev commented:

[Boris Shevchenko](https://app.asana.com/0/528285401193323/list) Do not working. Dapp doesn't show me the toast notifications.

**Comment by PolymathTeam** [comment]
➤ Stanislav Timofeev commented:

[Thomas Borrel](https://app.asana.com/0/610793545000470/list)
Now we have the toast notifications after 2 operations:
1. create account
2. apply to the provider

Do you think that's completed list? Why only on these operations?
