### ISSUE TITLE
If I'm not the issuer of a token I shouldn't be able to access any section on the dashboard on that token.

### ISSUE THREAD

**Issue by kotaru77** [PolymathNetwork/polymath-issuer#71]
A candidate pointed out that he was able to access the data on the dashboard of a token someone else deployed.

**Comment by kotaru77** [comment]
➤ Thomas Borrel commented:

Thank you [Pablo Ruiz](https://app.asana.com/0/511546395238232/list) - Had a similar bug as well. Will connect them both as duplicates.

**Comment by kotaru77** [comment]
➤ Boris Shevchenko commented:

[Matthew Woo](https://app.asana.com/0/461575372520165/list) this one is not related to the email flow refactoring

**Comment by kotaru77** [comment]
➤ Boris Shevchenko commented:

[Gopi](https://app.asana.com/0/697354420230415/list) how to detach it from parent task?

**Comment by kotaru77** [comment]
➤ Gopi commented:

[Boris Shevchenko](https://app.asana.com/0/528285401193323/list) it is currently a subtask under the story. I will create a separate Task and copy paste the content. Do you know what story it might belong to? Also, will you be able to get to this as part of this sprint?

**Comment by kotaru77** [comment]
➤ Gopi commented:

[Thomas Borrel](https://app.asana.com/0/610793545000470/list) Matt moved this as a subtask under the Refactoring email flow story along with few others. Apparently this one doesnt belong there. Do you know of any tricks to move this outside of this story without losing the history?

**Comment by kotaru77** [comment]
➤ Thomas Borrel commented:

Yup. Drag and drop works great!
I'll put it back under "EPICs & User Stories"

**Comment by PolymathTeam** [comment]
➤ Thomas Borrel commented:

[Gopi](https://app.asana.com/0/697354420230415/list) - I have a few tokens I have created which you should not be able to see: 1337; TEST-TEST; ---...--- are 3 examples.

**Comment by PolymathTeam** [comment]
➤ Gopi commented:

I confirm it is working as expected. It took me to the Signin page with Metamask first. After signing, it shows a blank screen for the above tokens.
